server:
    port: 8084
spring:
  data:
    mongodb:
      initialization-mode: always
      uri: mongodb://localhost:27017/ms-payment

rest-client:
  order:
    url: http://localhost:8085/api/v1/orders